### PR TITLE
Added contextMenu events to d.ts

### PR DESCRIPTION
**Pull request by Jet-Set-Willy**

### CODE REVIEW

**Comment by thomasdarvik** [comment]
@Jet-Set-Willy @lavrton 

Is there a reason why all functions defined in the types are `any`?. Isn't it better to do "the dirty work" and fix types from the bottom up? I end up having to use `any` on types in my code anyway when using Konva React, so there is no real reason to have types in the first place?

Say I use the `onContentContextMenu?(evt: any): void;`, I will still need to use `any` on the `evt`-return type, instead of actually having a proper type definition for `evt` and the returning types. Having functions defined as `any` just pushes the "`any`-problem" one step further down the error-tree.

Any thoughts on this?

**Comment by thomasdarvik** [comment]
Sorry for ranting here, I just see a couple of commits with types where everything is defined as `any` so it seems this is a recurring thing.

**Comment by lavrton** [comment]
@thomasdarvik correct types will be much better. I hope to revisit `react-konva` types when I finish migrating `konva` to full typescript in strict mode.

**Comment by thomasdarvik** [comment]
Cool. Will it help if I start defining some types and doing PRs on it to the project, or would you rather have me wait until you have started the typescript in strict mode migration?

**Comment by lavrton** [comment]
It will be helpful. We can adjust types later.

**Pull request merged**
