### PR TITLE
React 19 Upgrade

### PR DESCRIPTION
**Pull request by jackpope**
As described in https://github.com/konvajs/react-konva/issues/799, React 19 has some breaking changes that will require updates from third-party rendering libraries. I needed to get a new build of react-konva with React 19 working and I wanted to publish the updates here to share the required changes. Hopefully for a new release to go with React 19!

Changes in this PR
- Upgrade its-fine
- Add new reconciler methods to host config
- Update signature of `commitUpdate`
- Use React.act instead of timeouts in tests

### CODE REVIEW

**Comment by lavrton** [comment]
Thank you so much for your Pull Request. I will review it soon. 
Usually, I prefer to publish a new version AFTER a new react version is published.

**Comment by rjungbeck** [comment]
I tried to use the patch in my react-konva based app (that also uses react-konva-utils). 

I came across the same issues in react-konva-utils (at least I got similar errors messages). So we will probably need the same type of workaround there,

**Comment by PupoSDC** [comment]
I'm struggling getting this working on my own. I tried downloading the package, building it, and using that to patch package the current version... but I keep hitting this error: 

```
TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
```

@jackpope would you be so kind as to publish a version of this as a package?

**Comment by lavrton** [comment]
I can publish it as beta release. Will do this a bit later.

**Comment by lavrton** [comment]
I released 19.0.0-0. Try it.

**Comment by lavrton** [comment]
@jackpope I had some issues with `npm run build`. Do you have time to take a look? I temporarily removed the usage of `NoEventPriority`.

**Comment by PupoSDC** [comment]
First  testing looks like this is working. Thank you very much for this intermediate release. I will be testing it a bit more thoroughly in the coming days!

**Comment by Micnubinub** [comment]
Anyone else getting this in the newer versions? 
```js
TypeError: reactDom.findDOMNode is not a function
```

**Comment by lukedukeus** [comment]
> I'm struggling getting this working on my own. I tried downloading the package, building it, and using that to patch package the current version... but I keep hitting this error:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
> ```
> 
> @jackpope would you be so kind as to publish a version of this as a package?

Running into the same thing with the following:

```
    "konva": "^9.3.15",
    "react": "^19.0.0-rc-1460d67c-20241003",
    "react-dom": "^19.0.0-rc-1460d67c-20241003",
    "react-konva": "^19.0.0-1",
    "react-konva-utils": "^1.0.6",
```

Is there something I am missing?

**Comment by emmasaf** [comment]
> > I'm struggling getting this working on my own. I tried downloading the package, building it, and using that to patch package the current version... but I keep hitting this error:
> > ```
> > TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @jackpope would you be so kind as to publish a version of this as a package?
> 
> Running into the same thing with the following:
> 
> ```
>     "konva": "^9.3.15",
>     "react": "^19.0.0-rc-1460d67c-20241003",
>     "react-dom": "^19.0.0-rc-1460d67c-20241003",
>     "react-konva": "^19.0.0-1",
>     "react-konva-utils": "^1.0.6",
> ```
> 
> Is there something I am missing?

i switched into this versions ,and it start to work!

**Pull request merged**
