### PR TITLE
Make React Konva compatible with React v17

### PR DESCRIPTION
**Pull request by alexkuz**
This is a draft PR for future React release.

Tests don't work since Enzyme is not supporting React v17 yet (and probably won't support until the release). Still, it would be nice to publish this as `next` version or something.

### CODE REVIEW

**Comment by damiangreen** [comment]
@alexkuz  will this PR fix this issue?
https://github.com/konvajs/react-konva/issues/171

**Comment by alexkuz** [comment]
@damiangreen it should, yes. I think I've seen this one.

**Comment by damiangreen** [comment]
ok cool, this is one of only 2 libraries that dont work in our large  scale app with React 17, so maybe i can use your fork

**Comment by lavrton** [comment]
Try with `npm install react-konva@17.0.0-rc.1`.

**Comment by Siva-at-OFS** [comment]
I recently upgraded react version to 17.0.0 and found that react-konva@17.0.0-rc.1 is still not responding to clicks...

I'm using Stage, Layer, Group, Rect, Text  APIs from react-konva.

No error thrown and mouse clicks are still not detected.

The idea is to create a small rectangle like shape with specific text inside on mouse click at specific region of document.


image

I tried to use normal html canvas with javascript and the click function is working and I'm able to send the required clientX,clientY data to backend and other portions of the UI are responding to click event.

 But we couldn't see the "textfield" or "signature" rectangles (shown in the above image) appearing on click and its having an adverse impact on mobile UI where  the client is expected to sign at chosen locations.

Any suggestions?

**Comment by lavrton** [comment]
@Siva-at-OFS make a small online demo.

**Comment by Siva-at-OFS** [comment]
Here are the old and new versions being used with the same code.. 

Old versions:
Konva ~2.0.2
React-konva ~1.7.2
React ~16.3.2
React-dom ~16.3.2

New versions:
Konva ~8.3.0
React-konva ^17.0.0.rc.1
React ~17.0.0
ReactDom ~17.0.2

Click the below 👇 link for comparison of behaviour.
https://youtu.be/Gqm-2RvSYIM

I tried to use do things without using a library... Was able to send relevant data to backend but the feature in not working properly on mobile (which is a native Android application)

**Comment by lavrton** [comment]
I am sorry, I can't debug from the video. By the demo, I mean a small code example that work in unexpected way.  A link to https://codesandbox.io/

**Comment by Siva-at-OFS** [comment]
@lavrton , Sorry about that. I was also thinking what good is the video demo... Will try to create a sample code in codesandbox.

**Pull request merged**
